from typing import Protocol
from uuid import UUID

from app.domain.jobs import Job


class JobRepository(Protocol):
    def add(self, job: Job) -> None: ...
    def get(self, job_id: UUID) -> Job | None: ...
    def save(self, job: Job) -> None: ...
    def claim(self, job_id: UUID) -> bool: ...


class TaskQueue(Protocol):
    def enqueue(self, job_id: UUID) -> None: ...


class AgentOrchestrator(Protocol):
    async def run(self, prompt: str) -> str: ...


class FileStorage(Protocol):
    def put(self, key: str, content: bytes, content_type: str) -> None: ...
    def download_url(self, key: str, expires: int = 300) -> str: ...


class MailSender(Protocol):
    def send(self, to: str, subject: str, body: str) -> None: ...
